name: Unit Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14-dev"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python }}
      - name: Install toolchain
        run: pip install ruff
      - name: Unit tests
        run: python -m unittest tests/*/*.py
      - name: Lint
        run: ruff check secure tests
